sudo: required

language: python

services:
  - docker

env:

  global:
    - BUILD_ARGS="CONFIG_BUILD=false"

  matrix:
    - DOCKERFILE="9.0-Dockerfile" TESTS="1"
    - DOCKERFILE="10.0-Dockerfile" TESTS="1"
    - DOCKERFILE="11.0-Dockerfile" TESTS="1"

install:
  - git clone --depth=1 https://github.com/LasLabs/docker-quality-tools.git ${HOME}/docker-quality-tools
  - export PATH=${HOME}/docker-quality-tools/travis:${PATH}
  - travis_install_all

script:
  - travis_run_all

after_success:
  - travis_after_success_all
